# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: your-email@domain.com
brand: VioletteStyle
headline: Fashion Blogger Lifestyle & Beauty
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: /instademo # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: quan.zhou0117@gmail.com
instagram: violette.style

# Tracking
googleAnalitycsID: UA-83933844-1

